language: en
pipeline:
- name: WhitespaceTokenizer
- name: CRFEntityExtractor
- name: EntitySynonymMapper
- name: CountVectorsFeaturizer
  token_pattern: (?u)\b\w+\b
- name: EmbeddingIntentClassifier
- name: "ResponseSelector"
policies:
- name: FallbackPolicy
- name: AugmentedMemoizationPolicy
- name: FormPolicy
- name: MappingPolicy

