name: Publish Docker
on:
  push:
    branches: 
      - master
    paths:
    - "actions.py"
    - "Dockerfile"
    - "drinks.json"
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Dockerfile
    steps:
      - uses: actions/checkout@master
      - name: hadolint Dockerfile
        uses: burdzwastaken/hadolint-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HADOLINT_ACTION_DOCKERFILE_FOLDER: .
  deploy_image:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: realbtotharye/instill-action
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
